In [1]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)

[[5 8 9 5 0]
 [0 1 7 6 9]]


In [2]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)

[[5 8 9 5 0]
 [0 1 7 6 9]]
2


In [3]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)


In [4]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10


In [5]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32


In [6]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4


In [10]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9


In [11]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])



[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6


In [12]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])
print(arr[1])


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6
[0 1 7 6 9]


In [13]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])
print(arr[-2])


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6
[5 8 9 5 0]


In [17]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10)
print(arr)

5


In [33]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr)
print(arr[3])
print(arr[-2])
print(arr[3:9:2])
print(arr[::-1])
arr[2]=1.26

[5 8 9 5 0 0 1 7 6 9]
5
6
[5 0 7]
[9 6 7 1 0 0 5 9 8 5]


In [21]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr)
print(arr[3])
print(arr[-2])
print(arr[3:9:2])
print(arr[::-1])


[5 8 9 5 0 0 1 7 6 9]
5
6
[5 0 7]
[9 6 7 1 0 0 5 9 8 5]


In [25]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])
print(arr)

print(arr[-2])
print(arr[3:9:2])
print(arr[::-1])
print(arr[:2,:3])


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6
[[5 8 9 5 0]
 [0 1 7 6 9]]
[5 8 9 5 0]
[]
[[0 1 7 6 9]
 [5 8 9 5 0]]
[[5 8 9]
 [0 1 7]]


In [34]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1,4])
print(arr[-1,-2])
arr[1]=1.26
print(arr)


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
9
6
[[5 8 9 5 0]
 [1 1 1 1 1]]
