In [5]:
import numpy as np
arr=np.arange(1,21,1)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [5]:
import numpy as np
np.random.seed(0)
arr=np.random.randint(50,size=(4,5))
print(arr)
print(arr.itemsize)
print(arr.nbytes)

[[44 47  0  3  3]
 [39  9 19 21 36]
 [23  6 24 24 12]
 [ 1 38 39 23 46]]
4
80


In [3]:
import numpy as np
arr2=np.random.randint(0,50,size=(4,5))
print(arr2)
print(arr2.itemsize)
print(arr2.nbytes)

[[17  8 24 13 47]
 [42  8 30  7  3]
 [ 6 21 49  3  4]
 [24 49 43 12 26]]
4
80


In [4]:
import numpy as np
arr2=np.random.randint(0,50,size=(3,4))
print(arr2)


[[16 45 41 18]
 [15  0  4 25]
 [47 34 23  7]]
